openapi: 3.0.0
info:
  title: La Piasse API
  version: "1.0"
  license:
    name: MIT
servers:
  - url: http://localhost:8080
    description: Local development server
x-responses:
  - &response422
    description: Unprocessable Entity
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/ValidationError"
  - &response404
    description: The server cannot find the requested resource.
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/Error"
paths:
  /books:
    get:
      operationId: ListBooks
      parameters:
        - $ref: "#/components/parameters/Req.Paginated.page"
        - $ref: "#/components/parameters/Req.Paginated.page-size"
      responses:
        "200":
          description: The books were successfully retrieved.
          content:
            application/json:
              schema:
                type: object
                required:
                  - books
                  - pagination
                properties:
                  books:
                    type: array
                    items:
                      $ref: "#/components/schemas/Book.Show"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
    post:
      operationId: CreateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book.Edit"
      responses:
        "201":
          description: The book was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book.Show"
        "422": *response422
  /books/{bookId}:
    parameters:
      - name: bookId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/ID"
    get:
      operationId: GetBook
      responses:
        "200":
          description: The book was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book.Show"
        "404": *response404
    put:
      operationId: UpdateBook
      responses:
        "200":
          description: The book was successfully updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book.Show"
        "404": *response404
        "422": *response422
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book.Edit"
    delete:
      operationId: DeleteBook
      responses:
        "204":
          description: The book was successfully deleted.
        "404": *response404
  /health:
    get:
      operationId: health
      parameters: []
      responses:
        "200":
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
components:
  parameters:
    Req.Paginated.page:
      name: page
      in: query
      required: false
      description: The page number to retrieve (1-indexed).
      schema:
        type: integer
        minimum: 1
        default: 1
      explode: false
    Req.Paginated.page-size:
      name: page-size
      in: query
      required: false
      description: The maximum number of items to return per page.
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 50
      explode: false
  schemas:
    Amount:
      type: integer
      x-go-type: int64
    BadRequestError:
      type: object
      required:
        - title
        - status
        - type
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 422
        type:
          allOf:
            - $ref: "#/components/schemas/ErrorType"
          description: A URI reference that identifies the problem type.
          example: error:validation
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
      x-go-no-type-alias: true
    Book.Edit:
      type: object
      required:
        - name
        - default_currency_iso_code
      properties:
        name:
          type: string
        default_currency_iso_code:
          type: string
    Book.Show:
      type: object
      required:
        - id
        - created_at
        - updated_at
        - name
        - default_currency_iso_code
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        name:
          type: string
        default_currency_iso_code:
          type: string
    Error:
      type: object
      required:
        - title
        - status
        - type
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 422
        type:
          allOf:
            - $ref: "#/components/schemas/ErrorType"
          description: A URI reference that identifies the problem type.
          example: error:validation
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
      description: |-
        A machine-readable format for specifying errors in HTTP API responses
        based on RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807).
    ErrorType:
      type: string
      enum:
        - error:internal_error
        - error:bad_request
        - error:not_found
        - error:method_not_allowed
        - error:validation
    Exchange:
      type: object
      required:
        - date
        - register_id
        - description
        - status
      properties:
        date:
          type: string
          format: date
        register_id:
          $ref: "#/components/schemas/ID"
        cheque:
          type: string
        description:
          type: string
        memo:
          type: string
        status:
          $ref: "#/components/schemas/ExchangeStatus"
      allOf:
        - $ref: "#/components/schemas/Resource"
    ExchangeStatus:
      type: string
      enum:
        - uncleared
        - reconciling
        - cleared
    ExchangeWithSplits:
      type: object
      required:
        - splits
      properties:
        splits:
          type: array
          items:
            $ref: "#/components/schemas/Split"
      allOf:
        - $ref: "#/components/schemas/Exchange"
    FieldValidationError:
      type: object
      required:
        - field
        - message
        - validation
      properties:
        field:
          type: string
          description: The name of the invalid field.
        message:
          type: string
          description: A message describing why the field is invalid.
        validation:
          type: string
          description: The validation that failed.
        param:
          type: string
          description: Additional configuration related to the validation.
    Health:
      type: object
      required:
        - status
      properties:
        status:
          $ref: "#/components/schemas/ServerHealthStatus"
        reason:
          type: string
    ID:
      type: string
    InternalError:
      type: object
      required:
        - title
        - status
        - type
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 422
        type:
          allOf:
            - $ref: "#/components/schemas/ErrorType"
          description: A URI reference that identifies the problem type.
          example: error:validation
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Pagination:
      type: object
      required:
        - hasNext
      properties:
        hasNext:
          type: boolean
    Register:
      type: object
      required:
        - name
        - account_type
        - currency_iso_code
      properties:
        name:
          type: string
        account_type:
          $ref: "#/components/schemas/RegisterType"
        currency_iso_code:
          type: string
      allOf:
        - $ref: "#/components/schemas/Resource"
    RegisterType:
      type: string
      enum:
        - expense
        - income
        - asset
        - bank
        - card
        - institution
        - investment
        - liability
        - loan
    Resource:
      type: object
      required:
        - id
        - created_at
        - updated_at
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      description: Base model for all resources.
    ServerHealthStatus:
      type: string
      enum:
        - healthy
        - unhealthy
    Split:
      type: object
      required:
        - exchange_id
        - destination_register_id
        - amount
        - status
      properties:
        exchange_id:
          $ref: "#/components/schemas/ID"
        destination_register_id:
          $ref: "#/components/schemas/ID"
        amount:
          $ref: "#/components/schemas/Amount"
        counterpart_amount:
          $ref: "#/components/schemas/Amount"
        memo:
          type: string
        status:
          $ref: "#/components/schemas/ExchangeStatus"
      allOf:
        - $ref: "#/components/schemas/Resource"
    User:
      type: object
      required:
        - display_name
      properties:
        display_name:
          type: string
      allOf:
        - $ref: "#/components/schemas/Resource"
    ValidationError:
      type: object
      required:
        - title
        - status
        - type
        - validation_errors
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 422
        type:
          allOf:
            - $ref: "#/components/schemas/ErrorType"
          description: A URI reference that identifies the problem type.
          example: error:validation
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        validation_errors:
          type: array
          items:
            $ref: "#/components/schemas/FieldValidationError"
          description: A list of fields that failed validation.
      x-go-no-type-alias: true
