// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ErrorType.
const (
	ErrorTypeErrorBadRequest       ErrorType = "error:bad_request"
	ErrorTypeErrorInternalError    ErrorType = "error:internal_error"
	ErrorTypeErrorMethodNotAllowed ErrorType = "error:method_not_allowed"
	ErrorTypeErrorNotFound         ErrorType = "error:not_found"
	ErrorTypeErrorValidation       ErrorType = "error:validation"
)

// Defines values for ServerHealthStatus.
const (
	ServerHealthStatusHealthy   ServerHealthStatus = "healthy"
	ServerHealthStatusUnhealthy ServerHealthStatus = "unhealthy"
)

// BookEdit defines model for Book.Edit.
type BookEdit struct {
	DefaultCurrencyIsoCode string `json:"default_currency_iso_code"`
	Name                   string `json:"name"`
}

// BookShow defines model for Book.Show.
type BookShow struct {
	CreatedAt              time.Time `json:"created_at"`
	DefaultCurrencyIsoCode string    `json:"default_currency_iso_code"`
	Id                     string    `json:"id"`
	Name                   string    `json:"name"`
	UpdatedAt              time.Time `json:"updated_at"`
}

// Error A machine-readable format for specifying errors in HTTP API responses
// based on RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807).
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type ErrorType `json:"type"`
}

// ErrorType defines model for ErrorType.
type ErrorType string

// FieldValidationError defines model for FieldValidationError.
type FieldValidationError struct {
	// Field The name of the invalid field.
	Field string `json:"field"`

	// Message A message describing why the field is invalid.
	Message string `json:"message"`

	// Param Additional configuration related to the validation.
	Param *string `json:"param,omitempty"`

	// Validation The validation that failed.
	Validation string `json:"validation"`
}

// Health defines model for Health.
type Health struct {
	Reason *string            `json:"reason,omitempty"`
	Status ServerHealthStatus `json:"status"`
}

// ID defines model for ID.
type ID = string

// Pagination defines model for Pagination.
type Pagination struct {
	HasNext bool `json:"hasNext"`
}

// ServerHealthStatus defines model for ServerHealthStatus.
type ServerHealthStatus string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type ErrorType `json:"type"`

	// ValidationErrors A list of fields that failed validation.
	ValidationErrors []FieldValidationError `json:"validation_errors"`
}

// ReqPaginatedPage defines model for Req.Paginated.page.
type ReqPaginatedPage = int

// ReqPaginatedPageSize defines model for Req.Paginated.page-size.
type ReqPaginatedPageSize = int

// BooksIndexParams defines parameters for BooksIndex.
type BooksIndexParams struct {
	// Page The page number to retrieve (1-indexed).
	Page *ReqPaginatedPage `form:"page,omitempty" json:"page,omitempty"`

	// PageSize The maximum number of items to return per page.
	PageSize *ReqPaginatedPageSize `form:"page-size,omitempty" json:"page-size,omitempty"`
}

// BooksCreateJSONRequestBody defines body for BooksCreate for application/json ContentType.
type BooksCreateJSONRequestBody = BookEdit

// BooksUpdateJSONRequestBody defines body for BooksUpdate for application/json ContentType.
type BooksUpdateJSONRequestBody = BookEdit

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// BooksIndex request
	BooksIndex(ctx context.Context, params *BooksIndexParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BooksCreateWithBody request with any body
	BooksCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BooksCreate(ctx context.Context, body BooksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BooksDelete request
	BooksDelete(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BooksShow request
	BooksShow(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BooksUpdateWithBody request with any body
	BooksUpdateWithBody(ctx context.Context, bookId ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BooksUpdate(ctx context.Context, bookId ID, body BooksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Health request
	Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) BooksIndex(ctx context.Context, params *BooksIndexParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBooksIndexRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BooksCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBooksCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BooksCreate(ctx context.Context, body BooksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBooksCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BooksDelete(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBooksDeleteRequest(c.Server, bookId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BooksShow(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBooksShowRequest(c.Server, bookId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BooksUpdateWithBody(ctx context.Context, bookId ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBooksUpdateRequestWithBody(c.Server, bookId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BooksUpdate(ctx context.Context, bookId ID, body BooksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBooksUpdateRequest(c.Server, bookId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBooksIndexRequest generates requests for BooksIndex
func NewBooksIndexRequest(server string, params *BooksIndexParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/books")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "page-size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBooksCreateRequest calls the generic BooksCreate builder with application/json body
func NewBooksCreateRequest(server string, body BooksCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBooksCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewBooksCreateRequestWithBody generates requests for BooksCreate with any type of body
func NewBooksCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/books")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBooksDeleteRequest generates requests for BooksDelete
func NewBooksDeleteRequest(server string, bookId ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/books/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBooksShowRequest generates requests for BooksShow
func NewBooksShowRequest(server string, bookId ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/books/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBooksUpdateRequest calls the generic BooksUpdate builder with application/json body
func NewBooksUpdateRequest(server string, bookId ID, body BooksUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBooksUpdateRequestWithBody(server, bookId, "application/json", bodyReader)
}

// NewBooksUpdateRequestWithBody generates requests for BooksUpdate with any type of body
func NewBooksUpdateRequestWithBody(server string, bookId ID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/books/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthRequest generates requests for Health
func NewHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// BooksIndexWithResponse request
	BooksIndexWithResponse(ctx context.Context, params *BooksIndexParams, reqEditors ...RequestEditorFn) (*BooksIndexResponse, error)

	// BooksCreateWithBodyWithResponse request with any body
	BooksCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BooksCreateResponse, error)

	BooksCreateWithResponse(ctx context.Context, body BooksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*BooksCreateResponse, error)

	// BooksDeleteWithResponse request
	BooksDeleteWithResponse(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*BooksDeleteResponse, error)

	// BooksShowWithResponse request
	BooksShowWithResponse(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*BooksShowResponse, error)

	// BooksUpdateWithBodyWithResponse request with any body
	BooksUpdateWithBodyWithResponse(ctx context.Context, bookId ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BooksUpdateResponse, error)

	BooksUpdateWithResponse(ctx context.Context, bookId ID, body BooksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BooksUpdateResponse, error)

	// HealthWithResponse request
	HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error)
}

type BooksIndexResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data       []BookShow `json:"data"`
		Pagination Pagination `json:"pagination"`
	}
}

// Status returns HTTPResponse.Status
func (r BooksIndexResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BooksIndexResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BooksCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *BookShow
	JSON422      *ValidationError
}

// Status returns HTTPResponse.Status
func (r BooksCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BooksCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BooksDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r BooksDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BooksDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BooksShowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BookShow
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r BooksShowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BooksShowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BooksUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BookShow
	JSON404      *Error
	JSON422      *ValidationError
}

// Status returns HTTPResponse.Status
func (r BooksUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BooksUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
}

// Status returns HTTPResponse.Status
func (r HealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// BooksIndexWithResponse request returning *BooksIndexResponse
func (c *ClientWithResponses) BooksIndexWithResponse(ctx context.Context, params *BooksIndexParams, reqEditors ...RequestEditorFn) (*BooksIndexResponse, error) {
	rsp, err := c.BooksIndex(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBooksIndexResponse(rsp)
}

// BooksCreateWithBodyWithResponse request with arbitrary body returning *BooksCreateResponse
func (c *ClientWithResponses) BooksCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BooksCreateResponse, error) {
	rsp, err := c.BooksCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBooksCreateResponse(rsp)
}

func (c *ClientWithResponses) BooksCreateWithResponse(ctx context.Context, body BooksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*BooksCreateResponse, error) {
	rsp, err := c.BooksCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBooksCreateResponse(rsp)
}

// BooksDeleteWithResponse request returning *BooksDeleteResponse
func (c *ClientWithResponses) BooksDeleteWithResponse(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*BooksDeleteResponse, error) {
	rsp, err := c.BooksDelete(ctx, bookId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBooksDeleteResponse(rsp)
}

// BooksShowWithResponse request returning *BooksShowResponse
func (c *ClientWithResponses) BooksShowWithResponse(ctx context.Context, bookId ID, reqEditors ...RequestEditorFn) (*BooksShowResponse, error) {
	rsp, err := c.BooksShow(ctx, bookId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBooksShowResponse(rsp)
}

// BooksUpdateWithBodyWithResponse request with arbitrary body returning *BooksUpdateResponse
func (c *ClientWithResponses) BooksUpdateWithBodyWithResponse(ctx context.Context, bookId ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BooksUpdateResponse, error) {
	rsp, err := c.BooksUpdateWithBody(ctx, bookId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBooksUpdateResponse(rsp)
}

func (c *ClientWithResponses) BooksUpdateWithResponse(ctx context.Context, bookId ID, body BooksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BooksUpdateResponse, error) {
	rsp, err := c.BooksUpdate(ctx, bookId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBooksUpdateResponse(rsp)
}

// HealthWithResponse request returning *HealthResponse
func (c *ClientWithResponses) HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error) {
	rsp, err := c.Health(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthResponse(rsp)
}

// ParseBooksIndexResponse parses an HTTP response from a BooksIndexWithResponse call
func ParseBooksIndexResponse(rsp *http.Response) (*BooksIndexResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BooksIndexResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data       []BookShow `json:"data"`
			Pagination Pagination `json:"pagination"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBooksCreateResponse parses an HTTP response from a BooksCreateWithResponse call
func ParseBooksCreateResponse(rsp *http.Response) (*BooksCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BooksCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest BookShow
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseBooksDeleteResponse parses an HTTP response from a BooksDeleteWithResponse call
func ParseBooksDeleteResponse(rsp *http.Response) (*BooksDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BooksDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseBooksShowResponse parses an HTTP response from a BooksShowWithResponse call
func ParseBooksShowResponse(rsp *http.Response) (*BooksShowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BooksShowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BookShow
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseBooksUpdateResponse parses an HTTP response from a BooksUpdateWithResponse call
func ParseBooksUpdateResponse(rsp *http.Response) (*BooksUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BooksUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BookShow
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseHealthResponse parses an HTTP response from a HealthWithResponse call
func ParseHealthResponse(rsp *http.Response) (*HealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /books)
	BooksIndex(w http.ResponseWriter, r *http.Request, params BooksIndexParams)

	// (POST /books)
	BooksCreate(w http.ResponseWriter, r *http.Request)

	// (DELETE /books/{bookId})
	BooksDelete(w http.ResponseWriter, r *http.Request, bookId ID)

	// (GET /books/{bookId})
	BooksShow(w http.ResponseWriter, r *http.Request, bookId ID)

	// (PUT /books/{bookId})
	BooksUpdate(w http.ResponseWriter, r *http.Request, bookId ID)

	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /books)
func (_ Unimplemented) BooksIndex(w http.ResponseWriter, r *http.Request, params BooksIndexParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /books)
func (_ Unimplemented) BooksCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /books/{bookId})
func (_ Unimplemented) BooksDelete(w http.ResponseWriter, r *http.Request, bookId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /books/{bookId})
func (_ Unimplemented) BooksShow(w http.ResponseWriter, r *http.Request, bookId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /books/{bookId})
func (_ Unimplemented) BooksUpdate(w http.ResponseWriter, r *http.Request, bookId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// BooksIndex operation middleware
func (siw *ServerInterfaceWrapper) BooksIndex(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params BooksIndexParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", false, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page-size" -------------

	err = runtime.BindQueryParameter("form", false, false, "page-size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BooksIndex(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BooksCreate operation middleware
func (siw *ServerInterfaceWrapper) BooksCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BooksCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BooksDelete operation middleware
func (siw *ServerInterfaceWrapper) BooksDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookId" -------------
	var bookId ID

	err = runtime.BindStyledParameterWithOptions("simple", "bookId", chi.URLParam(r, "bookId"), &bookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BooksDelete(w, r, bookId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BooksShow operation middleware
func (siw *ServerInterfaceWrapper) BooksShow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookId" -------------
	var bookId ID

	err = runtime.BindStyledParameterWithOptions("simple", "bookId", chi.URLParam(r, "bookId"), &bookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BooksShow(w, r, bookId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BooksUpdate operation middleware
func (siw *ServerInterfaceWrapper) BooksUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookId" -------------
	var bookId ID

	err = runtime.BindStyledParameterWithOptions("simple", "bookId", chi.URLParam(r, "bookId"), &bookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BooksUpdate(w, r, bookId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/books", wrapper.BooksIndex)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/books", wrapper.BooksCreate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/books/{bookId}", wrapper.BooksDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/books/{bookId}", wrapper.BooksShow)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/books/{bookId}", wrapper.BooksUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.Health)
	})

	return r
}

type BooksIndexRequestObject struct {
	Params BooksIndexParams
}

type BooksIndexResponseObject interface {
	VisitBooksIndexResponse(w http.ResponseWriter) error
}

type BooksIndex200JSONResponse struct {
	Data       []BookShow `json:"data"`
	Pagination Pagination `json:"pagination"`
}

func (response BooksIndex200JSONResponse) VisitBooksIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type BooksCreateRequestObject struct {
	Body *BooksCreateJSONRequestBody
}

type BooksCreateResponseObject interface {
	VisitBooksCreateResponse(w http.ResponseWriter) error
}

type BooksCreate201JSONResponse BookShow

func (response BooksCreate201JSONResponse) VisitBooksCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

func (response ValidationError) VisitBooksCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type BooksDeleteRequestObject struct {
	BookId ID `json:"bookId"`
}

type BooksDeleteResponseObject interface {
	VisitBooksDeleteResponse(w http.ResponseWriter) error
}

type BooksDelete204Response struct {
}

func (response BooksDelete204Response) VisitBooksDeleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type BooksDelete404JSONResponse Error

func (response BooksDelete404JSONResponse) VisitBooksDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type BooksShowRequestObject struct {
	BookId ID `json:"bookId"`
}

type BooksShowResponseObject interface {
	VisitBooksShowResponse(w http.ResponseWriter) error
}

type BooksShow200JSONResponse BookShow

func (response BooksShow200JSONResponse) VisitBooksShowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type BooksShow404JSONResponse Error

func (response BooksShow404JSONResponse) VisitBooksShowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type BooksUpdateRequestObject struct {
	BookId ID `json:"bookId"`
	Body   *BooksUpdateJSONRequestBody
}

type BooksUpdateResponseObject interface {
	VisitBooksUpdateResponse(w http.ResponseWriter) error
}

type BooksUpdate200JSONResponse BookShow

func (response BooksUpdate200JSONResponse) VisitBooksUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type BooksUpdate404JSONResponse Error

func (response BooksUpdate404JSONResponse) VisitBooksUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

func (response ValidationError) VisitBooksUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse Health

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /books)
	BooksIndex(ctx context.Context, request BooksIndexRequestObject) (BooksIndexResponseObject, error)

	// (POST /books)
	BooksCreate(ctx context.Context, request BooksCreateRequestObject) (BooksCreateResponseObject, error)

	// (DELETE /books/{bookId})
	BooksDelete(ctx context.Context, request BooksDeleteRequestObject) (BooksDeleteResponseObject, error)

	// (GET /books/{bookId})
	BooksShow(ctx context.Context, request BooksShowRequestObject) (BooksShowResponseObject, error)

	// (PUT /books/{bookId})
	BooksUpdate(ctx context.Context, request BooksUpdateRequestObject) (BooksUpdateResponseObject, error)

	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// BooksIndex operation middleware
func (sh *strictHandler) BooksIndex(w http.ResponseWriter, r *http.Request, params BooksIndexParams) {
	var request BooksIndexRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BooksIndex(ctx, request.(BooksIndexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BooksIndex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BooksIndexResponseObject); ok {
		if err := validResponse.VisitBooksIndexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BooksCreate operation middleware
func (sh *strictHandler) BooksCreate(w http.ResponseWriter, r *http.Request) {
	var request BooksCreateRequestObject

	var body BooksCreateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BooksCreate(ctx, request.(BooksCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BooksCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BooksCreateResponseObject); ok {
		if err := validResponse.VisitBooksCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BooksDelete operation middleware
func (sh *strictHandler) BooksDelete(w http.ResponseWriter, r *http.Request, bookId ID) {
	var request BooksDeleteRequestObject

	request.BookId = bookId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BooksDelete(ctx, request.(BooksDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BooksDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BooksDeleteResponseObject); ok {
		if err := validResponse.VisitBooksDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BooksShow operation middleware
func (sh *strictHandler) BooksShow(w http.ResponseWriter, r *http.Request, bookId ID) {
	var request BooksShowRequestObject

	request.BookId = bookId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BooksShow(ctx, request.(BooksShowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BooksShow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BooksShowResponseObject); ok {
		if err := validResponse.VisitBooksShowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BooksUpdate operation middleware
func (sh *strictHandler) BooksUpdate(w http.ResponseWriter, r *http.Request, bookId ID) {
	var request BooksUpdateRequestObject

	request.BookId = bookId

	var body BooksUpdateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BooksUpdate(ctx, request.(BooksUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BooksUpdate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BooksUpdateResponseObject); ok {
		if err := validResponse.VisitBooksUpdateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
