// Package widgetapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package widgetapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for WidgetColor.
const (
	WidgetColorBlue WidgetColor = "blue"
	WidgetColorRed  WidgetColor = "red"
)

// Defines values for WidgetMergePatchUpdateColor.
const (
	WidgetMergePatchUpdateColorBlue WidgetMergePatchUpdateColor = "blue"
	WidgetMergePatchUpdateColorRed  WidgetMergePatchUpdateColor = "red"
)

// AnalyzeResult defines model for AnalyzeResult.
type AnalyzeResult struct {
	Analysis string `json:"analysis"`
	Id       string `json:"id"`
}

// Widget defines model for Widget.
type Widget struct {
	Color  WidgetColor `json:"color"`
	Id     string      `json:"id"`
	Weight int32       `json:"weight"`
}

// WidgetColor defines model for Widget.Color.
type WidgetColor string

// WidgetList defines model for WidgetList.
type WidgetList struct {
	Items []Widget `json:"items"`
}

// WidgetMergePatchUpdate defines model for WidgetMergePatchUpdate.
type WidgetMergePatchUpdate struct {
	Color  *WidgetMergePatchUpdateColor `json:"color,omitempty"`
	Id     *string                      `json:"id,omitempty"`
	Weight *int32                       `json:"weight,omitempty"`
}

// WidgetMergePatchUpdateColor defines model for WidgetMergePatchUpdate.Color.
type WidgetMergePatchUpdateColor string

// WidgetsCreateJSONRequestBody defines body for WidgetsCreate for application/json ContentType.
type WidgetsCreateJSONRequestBody = Widget

// WidgetsUpdateApplicationMergePatchPlusJSONRequestBody defines body for WidgetsUpdate for application/merge-patch+json ContentType.
type WidgetsUpdateApplicationMergePatchPlusJSONRequestBody = WidgetMergePatchUpdate

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// WidgetsList request
	WidgetsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WidgetsCreateWithBody request with any body
	WidgetsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	WidgetsCreate(ctx context.Context, body WidgetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WidgetsDelete request
	WidgetsDelete(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WidgetsRead request
	WidgetsRead(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WidgetsUpdateWithBody request with any body
	WidgetsUpdateWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	WidgetsUpdateWithApplicationMergePatchPlusJSONBody(ctx context.Context, id string, body WidgetsUpdateApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WidgetsAnalyze request
	WidgetsAnalyze(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) WidgetsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WidgetsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WidgetsCreate(ctx context.Context, body WidgetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WidgetsDelete(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsDeleteRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WidgetsRead(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsReadRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WidgetsUpdateWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsUpdateRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WidgetsUpdateWithApplicationMergePatchPlusJSONBody(ctx context.Context, id string, body WidgetsUpdateApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsUpdateRequestWithApplicationMergePatchPlusJSONBody(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WidgetsAnalyze(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWidgetsAnalyzeRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewWidgetsListRequest generates requests for WidgetsList
func NewWidgetsListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/widgets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWidgetsCreateRequest calls the generic WidgetsCreate builder with application/json body
func NewWidgetsCreateRequest(server string, body WidgetsCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewWidgetsCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewWidgetsCreateRequestWithBody generates requests for WidgetsCreate with any type of body
func NewWidgetsCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/widgets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewWidgetsDeleteRequest generates requests for WidgetsDelete
func NewWidgetsDeleteRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/widgets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWidgetsReadRequest generates requests for WidgetsRead
func NewWidgetsReadRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/widgets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWidgetsUpdateRequestWithApplicationMergePatchPlusJSONBody calls the generic WidgetsUpdate builder with application/merge-patch+json body
func NewWidgetsUpdateRequestWithApplicationMergePatchPlusJSONBody(server string, id string, body WidgetsUpdateApplicationMergePatchPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewWidgetsUpdateRequestWithBody(server, id, "application/merge-patch+json", bodyReader)
}

// NewWidgetsUpdateRequestWithBody generates requests for WidgetsUpdate with any type of body
func NewWidgetsUpdateRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/widgets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewWidgetsAnalyzeRequest generates requests for WidgetsAnalyze
func NewWidgetsAnalyzeRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/widgets/%s/analyze", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// WidgetsListWithResponse request
	WidgetsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WidgetsListResponse, error)

	// WidgetsCreateWithBodyWithResponse request with any body
	WidgetsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*WidgetsCreateResponse, error)

	WidgetsCreateWithResponse(ctx context.Context, body WidgetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*WidgetsCreateResponse, error)

	// WidgetsDeleteWithResponse request
	WidgetsDeleteWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*WidgetsDeleteResponse, error)

	// WidgetsReadWithResponse request
	WidgetsReadWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*WidgetsReadResponse, error)

	// WidgetsUpdateWithBodyWithResponse request with any body
	WidgetsUpdateWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*WidgetsUpdateResponse, error)

	WidgetsUpdateWithApplicationMergePatchPlusJSONBodyWithResponse(ctx context.Context, id string, body WidgetsUpdateApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*WidgetsUpdateResponse, error)

	// WidgetsAnalyzeWithResponse request
	WidgetsAnalyzeWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*WidgetsAnalyzeResponse, error)
}

type WidgetsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WidgetList
}

// Status returns HTTPResponse.Status
func (r WidgetsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WidgetsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WidgetsCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Widget
}

// Status returns HTTPResponse.Status
func (r WidgetsCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WidgetsCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WidgetsDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r WidgetsDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WidgetsDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WidgetsReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Widget
}

// Status returns HTTPResponse.Status
func (r WidgetsReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WidgetsReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WidgetsUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Widget
}

// Status returns HTTPResponse.Status
func (r WidgetsUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WidgetsUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WidgetsAnalyzeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AnalyzeResult
}

// Status returns HTTPResponse.Status
func (r WidgetsAnalyzeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WidgetsAnalyzeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// WidgetsListWithResponse request returning *WidgetsListResponse
func (c *ClientWithResponses) WidgetsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WidgetsListResponse, error) {
	rsp, err := c.WidgetsList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsListResponse(rsp)
}

// WidgetsCreateWithBodyWithResponse request with arbitrary body returning *WidgetsCreateResponse
func (c *ClientWithResponses) WidgetsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*WidgetsCreateResponse, error) {
	rsp, err := c.WidgetsCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsCreateResponse(rsp)
}

func (c *ClientWithResponses) WidgetsCreateWithResponse(ctx context.Context, body WidgetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*WidgetsCreateResponse, error) {
	rsp, err := c.WidgetsCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsCreateResponse(rsp)
}

// WidgetsDeleteWithResponse request returning *WidgetsDeleteResponse
func (c *ClientWithResponses) WidgetsDeleteWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*WidgetsDeleteResponse, error) {
	rsp, err := c.WidgetsDelete(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsDeleteResponse(rsp)
}

// WidgetsReadWithResponse request returning *WidgetsReadResponse
func (c *ClientWithResponses) WidgetsReadWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*WidgetsReadResponse, error) {
	rsp, err := c.WidgetsRead(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsReadResponse(rsp)
}

// WidgetsUpdateWithBodyWithResponse request with arbitrary body returning *WidgetsUpdateResponse
func (c *ClientWithResponses) WidgetsUpdateWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*WidgetsUpdateResponse, error) {
	rsp, err := c.WidgetsUpdateWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsUpdateResponse(rsp)
}

func (c *ClientWithResponses) WidgetsUpdateWithApplicationMergePatchPlusJSONBodyWithResponse(ctx context.Context, id string, body WidgetsUpdateApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*WidgetsUpdateResponse, error) {
	rsp, err := c.WidgetsUpdateWithApplicationMergePatchPlusJSONBody(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsUpdateResponse(rsp)
}

// WidgetsAnalyzeWithResponse request returning *WidgetsAnalyzeResponse
func (c *ClientWithResponses) WidgetsAnalyzeWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*WidgetsAnalyzeResponse, error) {
	rsp, err := c.WidgetsAnalyze(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWidgetsAnalyzeResponse(rsp)
}

// ParseWidgetsListResponse parses an HTTP response from a WidgetsListWithResponse call
func ParseWidgetsListResponse(rsp *http.Response) (*WidgetsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WidgetsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WidgetList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseWidgetsCreateResponse parses an HTTP response from a WidgetsCreateWithResponse call
func ParseWidgetsCreateResponse(rsp *http.Response) (*WidgetsCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WidgetsCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Widget
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseWidgetsDeleteResponse parses an HTTP response from a WidgetsDeleteWithResponse call
func ParseWidgetsDeleteResponse(rsp *http.Response) (*WidgetsDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WidgetsDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseWidgetsReadResponse parses an HTTP response from a WidgetsReadWithResponse call
func ParseWidgetsReadResponse(rsp *http.Response) (*WidgetsReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WidgetsReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Widget
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseWidgetsUpdateResponse parses an HTTP response from a WidgetsUpdateWithResponse call
func ParseWidgetsUpdateResponse(rsp *http.Response) (*WidgetsUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WidgetsUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Widget
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseWidgetsAnalyzeResponse parses an HTTP response from a WidgetsAnalyzeWithResponse call
func ParseWidgetsAnalyzeResponse(rsp *http.Response) (*WidgetsAnalyzeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WidgetsAnalyzeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AnalyzeResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /widgets)
	WidgetsList(w http.ResponseWriter, r *http.Request)

	// (POST /widgets)
	WidgetsCreate(w http.ResponseWriter, r *http.Request)

	// (DELETE /widgets/{id})
	WidgetsDelete(w http.ResponseWriter, r *http.Request, id string)

	// (GET /widgets/{id})
	WidgetsRead(w http.ResponseWriter, r *http.Request, id string)

	// (PATCH /widgets/{id})
	WidgetsUpdate(w http.ResponseWriter, r *http.Request, id string)

	// (POST /widgets/{id}/analyze)
	WidgetsAnalyze(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /widgets)
func (_ Unimplemented) WidgetsList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /widgets)
func (_ Unimplemented) WidgetsCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /widgets/{id})
func (_ Unimplemented) WidgetsDelete(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /widgets/{id})
func (_ Unimplemented) WidgetsRead(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /widgets/{id})
func (_ Unimplemented) WidgetsUpdate(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /widgets/{id}/analyze)
func (_ Unimplemented) WidgetsAnalyze(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// WidgetsList operation middleware
func (siw *ServerInterfaceWrapper) WidgetsList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WidgetsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WidgetsCreate operation middleware
func (siw *ServerInterfaceWrapper) WidgetsCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WidgetsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WidgetsDelete operation middleware
func (siw *ServerInterfaceWrapper) WidgetsDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WidgetsDelete(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WidgetsRead operation middleware
func (siw *ServerInterfaceWrapper) WidgetsRead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WidgetsRead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WidgetsUpdate operation middleware
func (siw *ServerInterfaceWrapper) WidgetsUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WidgetsUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WidgetsAnalyze operation middleware
func (siw *ServerInterfaceWrapper) WidgetsAnalyze(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WidgetsAnalyze(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/widgets", wrapper.WidgetsList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/widgets", wrapper.WidgetsCreate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/widgets/{id}", wrapper.WidgetsDelete)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/widgets/{id}", wrapper.WidgetsRead)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/widgets/{id}", wrapper.WidgetsUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/widgets/{id}/analyze", wrapper.WidgetsAnalyze)
	})

	return r
}

type WidgetsListRequestObject struct {
}

type WidgetsListResponseObject interface {
	VisitWidgetsListResponse(w http.ResponseWriter) error
}

type WidgetsList200JSONResponse WidgetList

func (response WidgetsList200JSONResponse) VisitWidgetsListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type WidgetsCreateRequestObject struct {
	Body *WidgetsCreateJSONRequestBody
}

type WidgetsCreateResponseObject interface {
	VisitWidgetsCreateResponse(w http.ResponseWriter) error
}

type WidgetsCreate200JSONResponse Widget

func (response WidgetsCreate200JSONResponse) VisitWidgetsCreateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type WidgetsDeleteRequestObject struct {
	Id string `json:"id"`
}

type WidgetsDeleteResponseObject interface {
	VisitWidgetsDeleteResponse(w http.ResponseWriter) error
}

type WidgetsDelete204Response struct {
}

func (response WidgetsDelete204Response) VisitWidgetsDeleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type WidgetsReadRequestObject struct {
	Id string `json:"id"`
}

type WidgetsReadResponseObject interface {
	VisitWidgetsReadResponse(w http.ResponseWriter) error
}

type WidgetsRead200JSONResponse Widget

func (response WidgetsRead200JSONResponse) VisitWidgetsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type WidgetsUpdateRequestObject struct {
	Id   string `json:"id"`
	Body *WidgetsUpdateApplicationMergePatchPlusJSONRequestBody
}

type WidgetsUpdateResponseObject interface {
	VisitWidgetsUpdateResponse(w http.ResponseWriter) error
}

type WidgetsUpdate200JSONResponse Widget

func (response WidgetsUpdate200JSONResponse) VisitWidgetsUpdateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type WidgetsAnalyzeRequestObject struct {
	Id string `json:"id"`
}

type WidgetsAnalyzeResponseObject interface {
	VisitWidgetsAnalyzeResponse(w http.ResponseWriter) error
}

type WidgetsAnalyze200JSONResponse AnalyzeResult

func (response WidgetsAnalyze200JSONResponse) VisitWidgetsAnalyzeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /widgets)
	WidgetsList(ctx context.Context, request WidgetsListRequestObject) (WidgetsListResponseObject, error)

	// (POST /widgets)
	WidgetsCreate(ctx context.Context, request WidgetsCreateRequestObject) (WidgetsCreateResponseObject, error)

	// (DELETE /widgets/{id})
	WidgetsDelete(ctx context.Context, request WidgetsDeleteRequestObject) (WidgetsDeleteResponseObject, error)

	// (GET /widgets/{id})
	WidgetsRead(ctx context.Context, request WidgetsReadRequestObject) (WidgetsReadResponseObject, error)

	// (PATCH /widgets/{id})
	WidgetsUpdate(ctx context.Context, request WidgetsUpdateRequestObject) (WidgetsUpdateResponseObject, error)

	// (POST /widgets/{id}/analyze)
	WidgetsAnalyze(ctx context.Context, request WidgetsAnalyzeRequestObject) (WidgetsAnalyzeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// WidgetsList operation middleware
func (sh *strictHandler) WidgetsList(w http.ResponseWriter, r *http.Request) {
	var request WidgetsListRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WidgetsList(ctx, request.(WidgetsListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WidgetsList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WidgetsListResponseObject); ok {
		if err := validResponse.VisitWidgetsListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// WidgetsCreate operation middleware
func (sh *strictHandler) WidgetsCreate(w http.ResponseWriter, r *http.Request) {
	var request WidgetsCreateRequestObject

	var body WidgetsCreateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WidgetsCreate(ctx, request.(WidgetsCreateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WidgetsCreate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WidgetsCreateResponseObject); ok {
		if err := validResponse.VisitWidgetsCreateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// WidgetsDelete operation middleware
func (sh *strictHandler) WidgetsDelete(w http.ResponseWriter, r *http.Request, id string) {
	var request WidgetsDeleteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WidgetsDelete(ctx, request.(WidgetsDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WidgetsDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WidgetsDeleteResponseObject); ok {
		if err := validResponse.VisitWidgetsDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// WidgetsRead operation middleware
func (sh *strictHandler) WidgetsRead(w http.ResponseWriter, r *http.Request, id string) {
	var request WidgetsReadRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WidgetsRead(ctx, request.(WidgetsReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WidgetsRead")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WidgetsReadResponseObject); ok {
		if err := validResponse.VisitWidgetsReadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// WidgetsUpdate operation middleware
func (sh *strictHandler) WidgetsUpdate(w http.ResponseWriter, r *http.Request, id string) {
	var request WidgetsUpdateRequestObject

	request.Id = id

	var body WidgetsUpdateApplicationMergePatchPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WidgetsUpdate(ctx, request.(WidgetsUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WidgetsUpdate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WidgetsUpdateResponseObject); ok {
		if err := validResponse.VisitWidgetsUpdateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// WidgetsAnalyze operation middleware
func (sh *strictHandler) WidgetsAnalyze(w http.ResponseWriter, r *http.Request, id string) {
	var request WidgetsAnalyzeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WidgetsAnalyze(ctx, request.(WidgetsAnalyzeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WidgetsAnalyze")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WidgetsAnalyzeResponseObject); ok {
		if err := validResponse.VisitWidgetsAnalyzeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
