name: PR Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy: &strategy
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - &checkout
        uses: actions/checkout@v4
      - &setup-go
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Test
        run: make test
        env:
          TEST_LOG: fail
      - name: Ensure tracked files were up to date
        run: ./scripts/git_tracked_are_unmodified
  build:
    runs-on: ${{ matrix.os }}
    strategy: *strategy
    steps:
      - *checkout
      - *setup-go
      - name: Build
        run: make build-only
      - &check-no-mod
        name: Ensure tracked files were up to date
        run: ./scripts/git_tracked_are_unmodified
  lint:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-go
      - name: Lint
        run: make lint-ci
      - name: Determine golangci-lint version
        id: golangci-lint-version
        run:
          echo "golangci-lint-version=$(go list -modfile=golangci-lint.mod -m github.com/golangci/golangci-lint/v2 | awk '{print $2}')" >> "$GITHUB_OUTPUT"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ steps.golangci-lint-version.outputs.golangci-lint-version }}
        env:
          GOEXPERIMENT: "jsonv2" # align with `Makefile` (export GOEXPERIMENT)
      - *check-no-mod
  gen:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-go
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.8" # align with /.nvmrc
      - name: Install JS dependencies
        run: npm ci
      - name: Generate
        run: make gen
      - *check-no-mod