name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.8" # align with /.nvmrc
      - name: Install JS dependencies
        run: npm ci
      - name: Generate
        run:
          make gen && ./scripts/git_tracked_are_unmodified
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test
        env:
          TEST_LOG: fail
